#-------molecule_install: true-------#
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ molecule_install_dependencies_list }}"

- name: check home path 
  ansible.builtin.debug:
   var: ansible_env.HOME 
  register: molecule_install_home 
  become: no

#-molecule_install_virtualenv: false | install to [ /home/user/.local/ ]
#-for sudo user
- name: upgrade setuptools
  ansible.builtin.pip:
    name: "setuptools"   
    state: present
    extra_args: "--upgrade --user"
  become: yes
  become_user: "{{ ansible_user }}"
  when: not molecule_install_virtualenv and ansible_user != "root"
  
- name: install molecule in home/user/.local 
  ansible.builtin.pip:
    name: "molecule[ {{ item }} ]"  
    state: present
    extra_args: "--user" 
  with_items: "{{ molecule_install_packages_list }}"
  become: yes
  become_user: "{{ ansible_user }}"  
  when: not molecule_install_virtualenv and ansible_user != "root"
  
- name: add path /.locale/bin to environment 
  ansible.builtin.shell:
    cmd: ". ./.profile"
  become: yes
  become_user: "{{ ansible_user }}"  
  when: not molecule_install_virtualenv and ansible_user != "root"
 
 #-for root
- name: upgrade setuptools
  ansible.builtin.pip:
    name: "setuptools"   
    state: present
  when: not molecule_install_virtualenv and ansible_user == "root"
  
- name: install molecule in /usr/bin
  ansible.builtin.pip:
    name: "molecule[ {{ item }} ]"  
    state: present    
  with_items: "{{ molecule_install_packages_list }}"  
  when: not molecule_install_virtualenv and ansible_user == "root"


  
#--molecule_install_virtualenv: true | install to virtualenv [ home/user/molecule ]
- name: Check the path for Python
  command: which python3
  register: molecule_check_python_3_path 
  when: molecule_install_virtualenv
  

- name: asdsa 
  debug:
   msg: "{{ ansible_env }} {{ molecule_install_home }}"




- name: install molecule in virtualenv
  ansible.builtin.pip:
    name: "molecule[ {{ item }} ]"
    version: ""
    state: present
    virtualenv: "{{ molecule_install_virtualenv_path }}"
    virtualenv_command: "{{ molecule_check_python_3_path.stdout }} -m venv"
    virtualenv_site_packages: "yes"
  become: yes
  become_user: "{{ ansible_user }}"
  with_items: "{{ molecule_install_packages_list }}"
  when: molecule_install_virtualenv
