---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ molecule_install_dependencies_list_redhat }}"

- name: for sudo user
  block:
    - name: upgrade pip
      ansible.builtin.pip:
        name: pip
        executable: pip3
        extra_args: --upgrade
   
    - name: switch to python3
      set_fact: ansible_python_interpreter=/usr/bin/python3

    - name: upgrade setuptools
      ansible.builtin.pip:
        name: "setuptools"
        state: present
        extra_args: "--upgrade --user"
      become: yes
      become_user: "{{ ansible_user }}"

    - name: install molecule in home/user/.local
      ansible.builtin.pip:
        name: "molecule[{{ item }}]"
        state: present
        extra_args: "--user --ignore-installed"
      with_items: "{{ molecule_install_packages_list }}"
      become: yes
      become_user: "{{ ansible_user }}"
  when: ansible_user != "root"

- name: for root user
  block:
    - name: upgrade setuptools
      ansible.builtin.pip:
        name: "setuptools"
        state: present
        extra_args: "--upgrade"  

    - name: install molecule
      ansible.builtin.pip:
        name: "molecule[{{ item }}]"
        state: present
        extra_args: "--ignore-installed"
      with_items: "{{ molecule_install_packages_list }}"
  when: ansible_user == "root"


