---
# molecule_install: true
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ molecule_install_dependencies_list_redhat }}"

- name: molecule_install_virtualenv - false
  block:
    # ansible_user: sudo
    - name: upgrade setuptools
      ansible.builtin.pip:
        name: "setuptools"
        state: present
        extra_args: "--upgrade --user"
      become: yes
      become_user: "{{ ansible_user }}"
      when: ansible_user != "root"

    - name: install molecule in home/user/.local
      ansible.builtin.pip:
        name: "molecule[{{ item }}]"
        state: present
        extra_args: "--user"
      with_items: "{{ molecule_install_packages_list }}"
      become: yes
      become_user: "{{ ansible_user }}"
      when: ansible_user != "root"

    # ansible_user: root
    - name: upgrade setuptools
      ansible.builtin.pip:
        name: "setuptools"
        state: present
      when: ansible_user == "root"

    - name: install molecule in /usr/bin
      ansible.builtin.pip:
        name: "molecule[{{ item }}]"
        state: present
      with_items: "{{ molecule_install_packages_list }}"
      when: ansible_user == "root"
  when: not molecule_install_virtualenv

- name: molecule_install_virtualenv - true
  block:
    - name: check the path for Python
      command: which python3
      register: molecule_check_python_3_path

    - name: define home directory for root
      set_fact:
        molecule_install_home_directory: "{{ ansible_env.HOME }}"
      when: ansible_user == "root"

    - name: define home directory for sudo user
      set_fact:
        molecule_install_home_directory: "{{ ansible_env.PWD }}"
      when: ansible_user != "root"

    - name: install molecule in virtualenv
      ansible.builtin.pip:
        name: "molecule[{{ item }}]"
        version: ""
        state: present
        virtualenv: "{{ molecule_install_home_directory }}/{{ molecule_install_virtualenv_name }}"
        virtualenv_command: "{{ molecule_check_python_3_path.stdout }} -m venv"
        virtualenv_site_packages: "yes"
      become: yes
      become_user: "{{ ansible_user }}"
      with_items: "{{ molecule_install_packages_list }}"
  when: molecule_install_virtualenv
