---
- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ molecule_install_dependencies_list_debian }}"

- name: check the path for Python
  command: which python3
  register: molecule_check_python_3_path

- name: define home directory for root
  set_fact:
    molecule_install_home_directory: "{{ ansible_env.HOME }}"
  when: ansible_user == "root"

- name: define home directory for sudo user
  set_fact:
    molecule_install_home_directory: "{{ ansible_env.PWD }}"
  when: ansible_user != "root"

- name: install molecule in virtualenv
  ansible.builtin.pip:
    name: "molecule[{{ item }}]"
    version: ""
    state: present
    virtualenv: "{{ molecule_install_home_directory }}/{{ molecule_install_virtualenv_name }}"
    virtualenv_command: "{{ molecule_check_python_3_path.stdout }} -m venv"
    virtualenv_site_packages: "yes"
  become: yes
  become_user: "{{ ansible_user }}"
  with_items: "{{ molecule_install_packages_list }}"