- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - python3-pip
      - libssl-dev
      - python3-venv
    state: present

- name: Ensure molecule support packages are installed in a virtual environment
  pip:
    name: "molecule[{{ item }}]"
    version: ""
    state: present
    virtualenv: "{{ molecule_install_virtualenv }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    virtualenv_site_packages: "false"
  with_items: "{{ molecule_install_list }}"
