- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - python3-pip
      - libssl-dev
      - python3-venv
    state: present

- name: install molecule in virtualenv
  ansible.builtin.pip:
    name: "molecule[ {{ item }} ]"
    version: ""
    state: present
    virtualenv: "{{ molecule_install_virtualenv }}"
    virtualenv_site_packages: "yes"
  with_items: "{{ molecule_install_list }}"
