---
- name: Converge
  hosts: all

  pre_tasks:
  - name: Unnessessary command
    ansible.builtin.shell:
      cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
    when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  roles:
    - role: darexsu.molecule
      vars:
        molecule_install: true
        ansible_user: root